### ISSUE TITLE
koyeb账号貌似无法激活

### ISSUE THREAD

**Issue by luckyxyz1981** [javtube/javtube-server-koyeb#1]
koyeb注册有好几个月了，中间换了好几个邮箱重新注册，登录后都是意思，还有其他选择的没
Your account will be validated in the coming days. We recorded a massive demand in the last month and onboarding is currently throttled to provide you with the best experience. You will receive an e-mail when your account is ready!

**Comment by windflyer** [comment]
Koyeb 注册不了，可以试试：mogenius（https://studio.mogenius.com/），支持Docker，具体部署方法可参考Koyeb的方法。

**Comment by luckyxyz1981** [comment]
> Koyeb 注册不了，可以试试：mogenius（[https://studio.mogenius.com/），支持Docker，具体部署方法可参考Koyeb的方法。](https://studio.mogenius.com/%EF%BC%89%EF%BC%8C%E6%94%AF%E6%8C%81Docker%EF%BC%8C%E5%85%B7%E4%BD%93%E9%83%A8%E7%BD%B2%E6%96%B9%E6%B3%95%E5%8F%AF%E5%8F%82%E8%80%83Koyeb%E7%9A%84%E6%96%B9%E6%B3%95%E3%80%82)

搞定了，谢谢
